=== pypi-data/pypi-mirror-270/packages/sapporo/sapporo-1.7.1-py3-none-any.whl/sapporo/auth_config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "The schema for the sapporo's auth config file",
  "type": "object",
  "properties": {
    "auth_enabled": {
      "type": "boolean",
      "description": "Enable or disable the authentication"
    },
    "auth_provider": {
      "type": "string",
      "description": "Specifies the type of authentication provider to use",
      "enum": [
        "local",
        "oidc"
      ]
    },
    "local_auth": {
      "type": "object",
      "description": "Settings for local authentication using JWT",
      "properties": {
        "jwt_secret_key": {
          "type": "string",
          "description": "The secret key used to sign JWTs"
        },
        "users": {
          "type": "array",
          "description": "List of users allowed to authenticate",
          "items": {
            "type": "object",
            "properties": {
              "username": {
                "type": "string"
              },
              "password": {
                "type": "string"
              }
            },
            "additionalProperties": false,
            "required": [
              "username",
              "password"
            ]
          },
          "additionalItems": false
        }
      },
      "additionalProperties": false,
      "required": [
        "jwt_secret_key",
        "users"
      ]
    },
    "oidc_auth": {
      "type": "object",
      "description": "Settings for OpenID Connect authentication",
      "properties": {
        "realm_url": {
          "type": "string",
          "description": "URL to the OIDC realm"
        },
        "username_claim": {
          "type": "string",
          "description": "JWT claim used as the username"
        }
      },
      "additionalProperties": false,
      "required": [
        "realm_url",
        "username_claim"
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "auth_enabled",
    "auth_provider"
  ],
  "dependencies": {
    "auth_provider": {
      "local": [
        "local_auth"
      ],
      "ordc": [
        "oidc_auth"
      ]
    }
  }
}

=== pypi-data/pypi-mirror-270/packages/sapporo/sapporo-1.7.1-py3-none-any.whl/sapporo/auth_config.json
{
  "auth_enabled": false,
  "auth_provider": "local",
  "local_auth": {
    "jwt_secret_key": "spr_secret_key_please_change_this",
    "users": [
      {
        "username": "spr_test_user",
        "password": "spr_test_password"
      }
    ]
  },
  "oidc_auth": {
    "realm_url": "http://localhost:8080/realms/sapporo-dev",
    "username_claim": "sub"
  }
}
